#ifndef ENGINEERROR_H
#define ENGINEERROR_H

enum class EngineError {
  GLFW_ERROR,
  GLAD_ERROR,
  SHADER_ERROR,
  TEXTURE_ERROR,
  GENERIC_ENGINE_ERROR,

  ASSET_LOADING_ERROR,
  FILE_IO_ERROR,
  COMPONENT_NOT_INITIALIZED,
  NOT_YET_IMPLEMENTED,
};

#endif
